### PR TITLE
Add support to raml 1.0

### PR DESCRIPTION
**Pull request by glodieu**

### CODE REVIEW

**Comment by glodieu** [comment]
That error in travis already exists before in pull request.

**Comment by marbemac** [comment]
Awesome, thanks for this guys! We'll take a look at it all on Monday. @rainum to comb through it, and figure out what's happening w Travis.

**Comment by marbemac** [comment]
We're going to update the Travis node version so that tests run (@rainum).

Everything looks good, but we'd like to continue supporting RAML 0.8 export. Moving to 1.0 only export would be a breaking change for many of our users unfortunately.

At the moment, we don't have a good way to support multiple spec versions in api-spec-converter. The two options I see are:

1) duplicate the entire RAML exporter, one for 0.8, and one for 1.0.
2) pass the version number into exporters, and then have the one raml exporter use that version number to tweak the export as appropriate.

I vote for #2. However, it's a bandaid - we are currently preparing an architecture document for v2 of api-spec-converter, and it will handle multiple versions in a much more robust way.

Open to suggestions!

**Comment by sichvoge** [comment]
How about providing different exporter for a specific version? For that you don't need to do any changes to the current, but that would mean you need to maintain two different versions and there might be many similarities.

**Comment by marbemac** [comment]
Yup that is option #1 above - we could certainly do that as a temporary solution, in order to get RAML 1.0 support out the door. If there are not many differences between the two versions, it might make sense to do option #2 above though - one exporter that is passed the version number.

@rainum and I are putting together an architecture document for a a significant update to this converter, which we'll share later this week. This will include a longer term solution to the spec versioning issue.

**Comment by sichvoge** [comment]
@glodieu @marbemac did we agree on a method to support both versions of RAML instead of replacing one?

**Comment by glodieu** [comment]
@sichvoge Yes. Do you think that I need to create a new issue "support raml 0.8 and 1.0" or use this one to maintain raml 0.8?

**Comment by sichvoge** [comment]
Can you quickly summarize the outcome. What are we going for? Option 1 or 2?

**Comment by glodieu** [comment]
Hi @sichvoge @marbemac We're going with option #2 but if we found many differences we'll change to option #1.

**Comment by marbemac** [comment]
@glodieu That sounds great, let me know if there is anything that we can do to help, or if you have questions! Looking forward to shipping this.

**Comment by glodieu** [comment]
Hi Marc, already finish. I created a baseraml,js with all common methods, raml08.js and raml10.js for the things regarding each version. Thanks!

**Comment by marbemac** [comment]
We're adding support for multiple content types to Stoplight, and have updated this library accordingly to take advantage of that. It's a work in progress over at https://github.com/stoplightio/api-spec-converter/tree/feature/mimetype-overhaul. We'll merge these changes into that branch, test everything, and then finally merge back into master.

Question: does RAML 1.0 support multiple mimetypes? If so, we'll update the exporter to take advantage of this multiple mimetype support as well.

**Comment by sichvoge** [comment]
@marbemac it does support the use of multiple mimetypes indeed. See [here](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#bodies).

**Comment by pytlesk4** [comment]
@marbemac exporter is already updated to support multiple mimetypes for RAML 1.0

**Comment by marbemac** [comment]
@sichvoge @glodieu Our build tools are going crazy with the addition of the raml1 parser package (basically not working). We just did an experiment adding webpack, to pre-compile a bundle.js of api-spec-converter and distribute it with the repository.

Without the raml1 package, bundle.js is 2.88mb.
With the raml1 package, bundle.js is 20mb (!!!).

Do you guys have any idea what's going on?

**Comment by marbemac** [comment]
Ah, just noticed these, which might be related:

https://github.com/raml-org/raml-js-parser-2/issues/361
https://github.com/raml-org/raml-js-parser-2/issues/432

I suspect something to do with the raml1 parser dependencies is causing the build tools we use for the Stoplight app to die when trying to compile everything.

**Comment by pytlesk4** [comment]
I removed raml 1.0 support from the [feature/mimetype-overhaul](https://github.com/stoplightio/api-spec-converter/tree/feature/mimetype-overhaul) for right now.

I created [feature/raml10](https://github.com/stoplightio/api-spec-converter/tree/feature/raml10) branch with raml1.0 support.

**Comment by sichvoge** [comment]
@marbemac thats a known problem we need to fix indeed. the size of the project is to big and we will try to make some improvements soon.

**Comment by marbemac** [comment]
@glodieu @sichvoge any ideas on the following error? This occurs when you try to build, with webpack, a project importing the raml1 package (when you include building the node_modules deps).

You can reproduce the issue by checking out the https://github.com/stoplightio/api-spec-converter/tree/babel-build-fail branch, running "npm i" and "npm run build". The webpack config used is in webpack.config.js.

Unfortunately this issue means we can't compile the stoplight codebase. We've spent quite a bit of time on it, and for now will have to just push the mimetype updates to master without raml 1.0 just yet. We do badly want to support 1.0 though!

```
> webpack --config ./webpack.config.js --progress --colors

 63% 366/409 build modules
<--- Last few GCs --->

   28568 ms: Mark-sweep 1396.6 (1456.5) -> 1396.6 (1456.5) MB, 853.4 / 0 ms [allocation failure] [GC in old space requested].
   29410 ms: Mark-sweep 1396.6 (1456.5) -> 1396.4 (1456.5) MB, 842.5 / 0 ms [allocation failure] [GC in old space requested].
   30234 ms: Mark-sweep 1396.4 (1456.5) -> 1396.4 (1456.5) MB, 824.0 / 0 ms [last resort gc].
   31071 ms: Mark-sweep 1396.4 (1456.5) -> 1396.2 (1456.5) MB, 836.6 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1ddd2f1e3ac1 <JS Object>
    1: parseLiteral [/Users/Marc/Sites/stoplight/yogi/node_modules/babylon/lib/parser/expression.js:~545] [pc=0x2e20ef9ee8e3] (this=0x123ad2dbd961 <a Parser with map 0x143363facd81>,value=0,type=0x3ef0bad3469 <String[14]: NumericLiteral>)
    2: parseExprAtom [/Users/Marc/Sites/stoplight/yogi/node_modules/babylon/lib/parser/expression.js:~387] [pc=0x2e20ef9babe6] (this=0x123ad2dbd961 <a Parser ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[1]    6094 abort      npm run build
```

**Comment by sichvoge** [comment]
@marbemac we will try to help investigating. haven't seen that before and looking around it might be typescript that cause issues, but i don't know.

**Comment by sichvoge** [comment]
Seems the problem is the typescript dependency from the parser. As the team is cleaning up legacy dependency, that typescript dep will be removed as well. Hope that will simplify the packaging significantly. We will probably publish a version tomorrow.

**Comment by marbemac** [comment]
With the new raml1 parser update, we can now compile! Will be working towards getting this in shape in into production asap. A quick check of exporting our todo demo yields some errors in api workbench that we have questions about. Otherwise, it's looking good.

1. We get "specifying unknown facet:$ref" due to the schema refs below. How are these meant to be handled in 1.0?
2. Can't quite figure out why the example in the image below is invalid.
3. Seems we need to update traits to be a map in the 1.0 exporter (instead of an array).

screen shot 2016-09-14 at 5 03 27 pm


```
#%RAML 1.0
title: To-do Demo
version: '1.0'
baseUri: 'http://todos.stoplight.io'
protocols:
  - HTTP
documentation:
  - title: To-do Demo
    content: |-
      ## Welcome

      This is a place to put general notes and extra information, for internal use.

      To get started designing/documenting this API, select a version on the left.
securitySchemes:
  'null':
    type: Pass Through
    describedBy: null
    description: null
/todos:
  displayName: todos
  description: ''
  '/{todoId}':
    displayName: '{todoId}'
    description: ''
    uriParameters:
      todoId:
        type: string
    get:
      displayName: GET_todo
      headers: {}
      responses:
        '200':
          body:
            application/json:
              $ref: '#/definitions/todo-full'
      queryParameters: {}
    put:
      displayName: PUT_todos
      body:
        application/json:
          $ref: '#/definitions/todo-partial'
          example: |-
            {
                "name": "my todo's new name",
                "completed": false
            }
      headers: {}
      responses:
        '200':
          body:
            application/json:
              $ref: '#/definitions/todo-full'
        '403':
          body:
            application/json:
              type: object
      queryParameters: {}
      securedBy:
        - null
    delete:
      displayName: DELETE_todo
      headers: {}
      responses:
        '204': {}
      queryParameters: {}
      securedBy:
        - null
  uriParameters: {}
  post:
    displayName: POST_todos
    body:
      application/json:
        $ref: '#/definitions/todo-partial'
        example: |-
          {
              "name": "my todo's name",
              "completed": false
          }
    headers: {}
    responses:
      '201':
        body:
          application/json:
            $ref: '#/definitions/todo-full'
      '403':
        body:
          application/json:
            type: object
            properties: {}
    queryParameters: {}
    securedBy:
      - null
  get:
    displayName: GET_todos
    headers: {}
    responses:
      '200':
        body:
          application/json:
            type: array
            items:
              $ref: '#/definitions/todo-full'
            example: |-
              [
                  {
                      "id": 17,
                      "name": "new lit item",
                      "completed": null,
                      "completed_at": null,
                      "created_at": "2014-08-28T14:14:28.494Z",
                      "updated_at": "2014-08-28T14:14:28.494Z"
                  },
                  {
                      "id": 18,
                      "name": "new lit item2",
                      "completed": null,
                      "completed_at": null,
                      "created_at": "2014-08-28T14:14:28.494Z",
                      "updated_at": "2014-08-28T14:14:28.494Z"
                  }
              ]
    queryParameters: {}
/mocked:
  displayName: mocked
  description: ''
  uriParameters: {}
  get:
    displayName: GET_mocked
    description: |-
      This is an example of a mocked endpoint. 

      This endpoint does not actually exist in the api - try visiting [http://todos.stoplight.io/mocked](http://todos.stoplight.io). You will see the default response (same as you get when you visit the root "/" url).

      We have defined a 200 response below, with an example, and then explicitly turned on mocking for this endpoint via the dropdown in the right sidebar.

      With this enabled, if you visit {your prism instance host}/mocked, you'll see the mocked example. You can find the mock server host for this API by clicking the "Design Dashboard" button at the top of this screen. You can also try sending a test request by clicking "send test request" button in the right sidebar.
    headers: {}
    responses:
      '200':
        body:
          application/json:
            type: object
            properties:
              this:
                type: string
              mocked:
                type: boolean
            example: |-
              {
                  "this": "is",
                  "mocked": true
              }
    queryParameters: {}
types:
  user: |-
    {
        "type": "object",
        "properties": {
            "name": {
                "type": "string"
            }
        }
    }
  todo-partial: |-
    {
        "type": "object",
        "properties": {
            "name": {
                "type": "string"
            },
            "completed": {
                "type": [
                    "boolean",
                    "null"
                ]
            }
        },
        "required": [
            "name"
        ]
    }
  todo-full: |-
    {
        "allOf": [
            {
                "$ref": "#/definitions/todo-partial"
            },
            {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "completed_at": {
                        "type": [
                            "string",
                            "null"
                        ],
                        "format": "date-time"
                    },
                    "created_at": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "updated_at": {
                        "type": "string",
                        "format": "date-time"
                    }
                },
                "required": [
                    "id"
                ]
            }
        ]
    }
traits:
  - standardErrors:
      responses:
        '401':
          body:
            application/json:
              type: object
        '404':
          body:
            application/json:
              type: object
              properties:
                foo:
                  type: string
                bar:
                  type: string
  - standardErrors:
      responses:
        '403':
          body:
            application/json:
              type: object
              properties:
                message:
                  type: string
              required:
                - message
              example: |-
                {
                    "message": "NOT AUTHORIZED"
                }
        '404':
          body:
            application/json:
              type: object
              properties:
                status:
                  type: string
                error:
                  type: string
              required:
                - status
                - error
              example: |-
                {
                    "status": "404",
                    "error": "Not Found"
                }
        '500':
          body:
            application/json:
              type: object
  - paged:
      queryParameters:
        limit:
          type: integer
          description: This is how it works.
          maximum: 100
        skip:
          type: string
```

**Comment by glodieu** [comment]
Hi Marc, 
Could you please share me source file used to generate such raml file?
Thanks!

**Comment by sichvoge** [comment]
References are handled directly. So lets assume you have:

```yaml
type: object
required:
- name
properties:
  name:
    type: string
  address:
    $ref: '#/definitions/Address'
  age:
    type: integer
    format: int32
    minimum: 0
```

that converts into:

```yaml
type: object
properties:
  name:
    type: string
  address:
    type: Address
    required: false
  age:
    type: integer
    format: int32
    minimum: 0
    required: false
```

**Comment by marbemac** [comment]
Hmm, so are $refs not supported? It's a common pattern to make the body definition a ref to a model. For example, /users returns an array of user models, /user/{id} a single user model, etc. Those have $ref right there in the root (like in the base below).

```
post:
    displayName: POST_todos
    body:
      application/json:
        $ref: '#/definitions/todo-partial'
```

**Comment by sichvoge** [comment]
This in RAML is:

```yaml
post:
    displayName: POST_todos
    body:
      application/json:
        type: todo-partial

**Comment by sichvoge** [comment]
> 3. Seems we need to update traits to be a map in the 1.0 exporter (instead of an array).

yes it needs to be a map. what i also realised is that there are a lot of empty nodes, we should check if a node is empty and if yes not create it.

**Comment by marbemac** [comment]
AH, ok - so we just need to add support for re-writing those root $refs to that format.

I'm ok with the empty node change.

Any idea on the example property in the image above?

**Comment by sichvoge** [comment]
not sure if that works with all ;) i have seen that you can actually do `$ref` on paths as well which does not have anything to do with a data model. but if you talk about the occasions where you ref another data model; yes.

**Comment by glodieu** [comment]
Hi Marc,
Regarding $ref stuff, I want to explain you my changes about that.
When '$ref' from swagger or 'type' from raml is parsed, it's converted to 'ref' attribute in the parser model.
Example:
'$ref' swagger -> 'ref' parser model
'type' raml -> 'ref' parser model

When you export to swagger or raml, 'ref' attribute is converted to '$ref' or 'type' depends of the export.
'ref' parser model -> '$ref' swagger
'ref' parser model -> 'type' raml

If you have any doubt, please let me know.

**Comment by marbemac** [comment]
@glodieu makes sense! I've pulled in all of your most recent changes to the raml10 branch, and a whole lot of fixes and changes from us. It's in pretty good shape, the biggest issue right now is raml import.

https://github.com/stoplightio/api-spec-converter/tree/raml10

Could you take a look at https://github.com/stoplightio/api-spec-converter/blob/raml10/lib/importers/baseraml.js#L329-L370 and import in general, to fix it up? I wasn't quite sure how to use the raml1 parser - looks like the trait on line 336 there is some sort of special object from your library.

Thanks in advance, we're almost there!

**Comment by sichvoge** [comment]
QQ: It seems there is an exporter and importer for RAML 1.0; does that mean we can also go from RAML 1.0 > Swagger 2.0 already?

**Comment by marbemac** [comment]
@sichvoge yup! That should be possible as soon as we can fix up some of the issues with the raml importer. I don't quite understand the raml1 parser yet, and the objects and methods on those objects that it returns.

@glodieu did you have a chance to check out the code I linked above? I've been trying to figure out what methods are available on the TraitImpl object  from these docs:

https://raml-org.github.io/raml-js-parser-2/modules/_src_index_.html

but can't seem to figure it out. It might make sense to add some raml08/raml10 -> swagger mapping tests (instead of just swagger -> raml). I'll add one to get us started, in the next few hours.

**Comment by marbemac** [comment]
I'll also copy over your latest changes to the raml10 branch - what's the best way to move forward - I'm thinking we just add @glodieu as a contributor so that we can collaborate directly on that branch.

**Comment by sichvoge** [comment]
Are you guys really work with the top-level functions instead of the much easier to use JSON object? @glodieu can you elaborate?

**Comment by sichvoge** [comment]
BTW, I've got a very good example that waits for you to be sure that its working fine. https://github.com/raml-org/raml-examples/tree/master/others/world-music-api

Its a complete set of maybe 80% of the RAML 1.0 capabilities.

**Comment by marbemac** [comment]
Yeah I just started digging into the new raml importer files (w the raml1 parser), and am not quite sure how the top-level functions work or even what properties / functions are available for the various objects.

Sweet on that world music api example - we'd need to produce the "expected" swagger given that RAML file. What I'm thinking is re-working the tests to work like this:

```
/test
   /data
      /reversable
        /swagger
          example1.json
          examle2.json
        /raml
          example1.yaml
          examle2.yaml
      /swagger-import
        /swagger
          example1.json
        /raml
          example1.yaml
      /raml-import
        /swagger
          example1.json
        /raml
          example1.yaml

The test suite would enumerate those folders (or we could just have a config object that describes the cases). 

The test suite would run all the reversible files in both directions swagger -> raml and raml -> swagger, and assert equality.

The test suite would run all of the swagger-import folder swagger -> raml and assert the resulting raml is equal to the one expected.

The test suite would run all of the raml-import folder raml -> swagger and assert the resulting swagger is equal to the one expected.
```

This would make it much easier to just drop examples in, to beef up the case coverage. Right now most of the tests just duplicate the same logic to setup the importer, do the import one direction, then the other direction, then assert the result is equal to what we expect.

**Comment by sichvoge** [comment]
Sounds good. Regarding the top-level; at some point we will remove that from the parser since no one really uses it vs the JSON representation. So maybe in the next iteration we should use the JSON object. Might be to late now, since we have deliveries on our side ;)

**Comment by marbemac** [comment]
JSON representation sounds much nicer - I did not know that was an option. I'm ok shipping this version w the top-level functions, but yes makes sense to update soon after. We just need to figure out the raml import side of things now, and we're in good shape.

**Comment by marbemac** [comment]
@glodieu I've merged in all of your recent changes, along with our own, to the raml10 branch. You should have access to contribute directly there now - could you start doing that?

I also added an example failing raml import case:
https://github.com/stoplightio/api-spec-converter/commit/761df5a1b857071675772a394687971540234180

Could you help out cleaning up usage of the raml1 parser as it relates to importing? I'm not sure how it all works.

Thanks! Let me know if you have any questions.

**Comment by marbemac** [comment]
I merged these latest changes into the raml10 branch. Could you please start making changes there? Managing both branches is time consuming (and error prone).

For the moment, I commented out the traits import here: https://github.com/stoplightio/api-spec-converter/commit/9793157816c62ab10ba34ab10b36a0e5bcbd53fa.

But in general, raml import isn't using the parser correctly at all, so nothing "really" works, even though no errors are thrown. Any help on that would be appreciated!

**Comment by glodieu** [comment]
Hi @marbemac, I'm a little confuse about trait tests that you added in raml10 branch.
If I move such test to master branch (it doesn't have any changes by us), it fails.
I thought that the fails came from my changes.
Thanks in advance.

Here is the test output:
  1) Converter convert should convert import traits from raml 0.8 to swagger:

      AssertionError: expected { Object (swagger, schemes, ...) } to deeply equal { Object (swagger, schemes, ...) }
      + expected - actual

       {
         "basePath": "/foo"
         "consumes": [
           "application/json"
      +    "application/xop+xml"
         ]
         "definitions": {
           "user": {
             "properties": {
           "description": ""
           "title": "Simple API"
           "version": ""
         }
      +  "parameters": {
      +    "trait:myTrait:authorization": {
      +      "description": ""
      +      "in": "header"
      +      "name": "authorization"
      +      "type": "string"
      +    }
      +    "trait:myTrait:limit": {
      +      "in": "query"
      +      "name": "limit"
      +      "type": "string"
      +    }
      +    "trait:myTrait:page": {
      +      "in": "query"
      +      "name": "page"
      +      "type": "string"
      +    }
      +  }
         "paths": {
           "/users": {
             "get": {
      +        "consumes": []
               "description": ""
               "operationId": "GET_users"
               "parameters": [
                 {
      -            "in": "query"
      -            "name": "page"
      -            "required": false
      -            "type": "string"
      +            "$ref": "#/parameters/trait:myTrait:page"
                 }
                 {
      -            "in": "query"
      -            "name": "limit"
      -            "required": false
      -            "type": "string"
      +            "$ref": "#/parameters/trait:myTrait:limit"
                 }
                 {
      -            "description": ""
      -            "in": "header"
      -            "name": "authorization"
      -            "required": false
      -            "type": "string"
      +            "$ref": "#/parameters/trait:myTrait:authorization"
                 }
               ]
      +        "produces": []
               "responses": {
                 "200": {
                   "description": ""
                   "schema": {
                     "$ref": "#/definitions/user"
                   }
                 }
               }
      -        "summary": ""
      +        "summary": "Users"
             }
           }
         }
         "produces": [
      -    "application/json"
      +    "application/EDIFACT"
         ]
         "schemes": [
           "http"
           "https"
         ]
      +  "securityDefinitions": {
      +    "apikey": {
      +      "in": "query"
      +      "name": "apikey"
      +      "type": "apiKey"
      +    }
      +  }
         "swagger": "2.0"
       }

      at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at Assertion.ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at test/lib/converter.js:146:37
      at lib/converter.js:9:2241

**Comment by glodieu** [comment]
Thanks Marc, continue working on this.

**Comment by marbemac** [comment]
Merged into master & released!

**Comment by sichvoge** [comment]
@marbemac any release notes that we can refer back to? I don't see an entry on the releases tab

**Pull request closed without merging**
